require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "features/support/env.rb"
    - "lib/tasks/cucumber.rake"
    - "script/cucumber"
    - "spec/dummy/**/*"
    - "spec/i18n_spec.rb"
    - "vendor/**/*"
    - ".git/**/*"

  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Extra details are not displayed in offense messages by default. Change
  # behavior by overriding ExtraDetails, or by giving the
  # `-E/--extra-details` option.
  ExtraDetails: false
  # Additional cops that do not reference a style guide rule may be enabled by
  # default. Change behavior by overriding StyleGuideCopsOnly, or by giving
  # the --only-guide-cops option.
  StyleGuideCopsOnly: false
  # What version of the Ruby interpreter is the inspected code intended to
  # run on? (If there is more than one, set this to the lowest version.)
  TargetRubyVersion: 2.7

# Layout/EmptyLinesAroundAttributeAccessor:
#   Enabled: true

Layout/HashAlignment:
  Exclude:
    - "config/initializers/simple_form.rb"

Layout/LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 80
  Enabled: true
  Exclude:
    - "config/initializers/simple_form.rb"
    - "config/initializers/simple_form_bootstrap.rb"

# Layout/SpaceAroundMethodCallOperator:
#   Enabled: true

# Layout/SpaceBeforeFirstArg:
#   Enabled: true

# Lint/BinaryOperatorWithIdenticalOperands:
#   Enabled: true

# Lint/DeprecatedOpenSSLConstant:
#   Enabled: true

# Lint/DuplicateElsifCondition:
#   Enabled: true

# Lint/DuplicateRescueException:
#   Enabled: true

# Lint/EmptyConditionalBody:
#   Enabled: true

# Lint/FloatComparison:
#   Enabled: true

# Lint/MissingSuper:
#   Enabled: true

# Lint/MixedRegexpCaptureTypes:
#   Enabled: true

# Lint/OutOfRangeRegexpRef:
#   Enabled: true

# Lint/RaiseException:
#   Enabled: true

# Lint/SelfAssignment:
#   Enabled: true

# Lint/StructNewOverride:
#   Enabled: true

# Lint/TopLevelReturnWithArgument:
#   Enabled: true

# Lint/UnreachableLoop:
#   Enabled: true

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"
    - "**/*.gemspec"
    - "config/routes.rb"
    - "config/initializers/simple_form_bootstrap.rb"

# Metrics/MethodLength:
#   Enabled: true

# Performance/AncestorsInclude:
#   Enabled: true

# Performance/BigDecimalWithNumericArgument:
#   Enabled: true

# Performance/RedundantSortBlock:
#   Enabled: true

# Performance/RedundantStringChars:
#   Enabled: true

# Performance/ReverseFirst:
#   Enabled: true

# Performance/SortReverse:
#   Enabled: true

# Performance/Squeeze:
#   Enabled: true

# Performance/StringInclude:
#   Enabled: true

# Rails/ActiveRecordCallbacksOrder:
#   Enabled: true

# Rails/FindById:
#   Enabled: true

# Rails/Inquiry:
#   Enabled: true

# Rails/MailerName:
#   Enabled: true

# Rails/MatchRoute:
#   Enabled: true

# Rails/NegateInclude:
#   Enabled: true

# Rails/Pluck:
#   Enabled: true

# Rails/PluckId:
#   Enabled: true

# Rails/PluckInWhere:
#   Enabled: true

# Rails/RenderInline:
#   Enabled: true

# Rails/RenderPlainText:
#   Enabled: true

# Rails/ShortI18n:
#   Enabled: true

# Rails/WhereExists:
#   Enabled: true

# Style/AccessorGrouping:
#   Enabled: true

# Style/ArrayCoercion:
#   Enabled: true

# Style/BisectedAttrAccessor:
#   Enabled: true

# Style/CaseLikeIf:
#   Enabled: true

# Style/ExponentialNotation:
#   Enabled: true

# Style/ExplicitBlockArgument:
#   Enabled: true

# Style/GlobalStdStream:
#   Enabled: true

# Style/HashAsLastArrayItem:
#   Enabled: true

# Style/HashEachMethods:
#   Enabled: true

# Style/HashLikeCase:
#   Enabled: true

# Style/HashTransformKeys:
#   Enabled: true

# Style/HashTransformValues:
#   Enabled: true

# Style/OptionalBooleanParameter:
#   Enabled: true

# Style/RedundantAssignment:
#   Enabled: true

# Style/RedundantFetchBlock:
#   Enabled: true

# Style/RedundantFileExtensionInRequire:
#   Enabled: true

# Style/RedundantRegexpCharacterClass:
#   Enabled: true

# Style/RedundantRegexpEscape:
#   Enabled: true

Style/RegexpLiteral:
  Exclude:
    - "**/*.gemspec"

# Style/SingleArgumentDig:
#   Enabled: true

# Style/SlicingWithRange:
#   Enabled: true

# Style/StringConcatenation:
#   Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
