inherit_from: ../.rubocop.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpecRails/InferredSpecType:
  Inferences:
    concepts: service
    decorators: decorator
    services: service
