inherit_from: ../.rubocop.yml

require: rubocop-rspec

Metrics/ModuleLength:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/factories/**/*.rb

Style/Documentation:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - spec/factories/**/*.rb

Style/WordArray:
  Enabled: false
