inherit_from: ../.rubocop.yml

require: rubocop-rspec

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpec/Rails/InferredSpecType:
  Inferences:
    concepts: service
    decorators: decorator
    services: service
