inherit_from: ../.rubocop.yml

plugins:
  - rubocop-factory_bot
  - rubocop-rspec

require:
  - rubocop-capybara
  - rubocop-rspec_rails

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

RSpecRails/InferredSpecType:
  Inferences:
    concepts: service
    decorators: decorator
    services: service
