name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.5

    - name: "Cache gems"
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: "Install gems"
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --without documentation

    - name: "Run rspec"
      run: bundle exec rspec

    - name: Run RuboCop
      run: |
        bundle exec rubocop --parallel

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
