name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v1

    - name: Cache Ruby
      uses: actions/cache@v1
      id: ruby-cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.5

    - name: Install Ruby 2.6.5
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.6.5
        cache-available: ${{ steps.ruby-cache.outputs.cache-hit == 'true' }}

    - name: "Cache gems"
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Insall sqlite
      run: |
        apt-get install sqlite3

    - name: "Install gems"
      run: |
        gem update --system
        gem update bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --without documentation

    - name: "Run rspec"
      run: bundle exec rspec

    - name: Run RuboCop
      run: |
        bundle exec rubocop --parallel

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
