name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v1

    - name: Cache Ruby
      uses: actions/cache@v1
      id: ruby-cache
      with:
        path: ~/local/rubies
        key: ruby-2.6.6

    - name: Install Ruby 2.6.6
      uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.6.6
        cache-available: ${{ steps.ruby-cache.outputs.cache-hit == 'true' }}

    - name: Insall sqlite
      run: |
        sudo apt-get update
        sudo apt-get install libmysqlclient-dev libpq-dev libsqlite3-dev libncurses5-dev
        sudo apt-get install -y sqlite3

    - name: "Cache gems"
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: "Install gems"
      run: |
        gem install bundler  --no-document
        bundle config set without 'documentation'
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: "Run rspec"
      run: |
        bin/rails app:db:environment:set RAILS_ENV=test
        bin/rails app:db:migrate RAILS_ENV=test
        bin/rails app:db:reset RAILS_ENV=test
        bundle exec rspec

    - name: Run RuboCop
      run: |
        bundle exec rubocop --parallel
