name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    env:
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

#    - name: "Cache Ruby"
#      uses: actions/cache@v3
#      id: ruby-cache
#      with:
#        path: ~/local/rubies
#        key: ruby-3.2.x

      - name: "Install Ruby 3.2.x"
        uses: ruby/setup-ruby@v1
        id: ruby
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: "Install sqlite"
        run: |
          sudo apt-get update
          sudo apt-get install libmysqlclient-dev libpq-dev libsqlite3-dev libncurses5-dev
          sudo apt-get install -y sqlite3

      - name: "Prepare the database"
        run: |
          bin/rails app:db:environment:set RAILS_ENV=test
          bin/rails app:db:migrate RAILS_ENV=test
          bin/rails app:db:reset RAILS_ENV=test

      - name: "Run rspec"
        run: |
          bundle exec rspec

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bundle audit --update
#      - name: Security audit application code
#        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
